steps:
# Build the container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-build-flask-demo', '.']
# Push the container to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-build-flask-demo']
# Deploy container to CloudRun
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
#  args: 
#    - 'run'
#    - 'deploy'
#    - 'flask-demo'
#    - '--image'
#    - 'gcr.io/$PROJECT_ID/cloud-build-flask-demo'
#    - '--region'
#    - 'us-east1'
#    - '--platform'
#    - 'managed'
#    - '--service-account'
#    - 'flask-demo-account@automl-200918-1217.iam.gserviceaccount.com'
#    - '--allow-unauthenticated'
images:
- gcr.io/$PROJECT_ID/cloud-build-flask-demo
