# This is a basic workflow to help you get started with Actions

name: Builds a Docker container and publishes to GCR

on:
  push:
    branches: master
  pull_request:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-accounts/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID}}
        service_account_key: ${{ secrets.CB_SERVICE_ACCOUNT }}
    
    # Submit build job
    - run: |-
        gcloud builds submit --config cloudbuild.yaml
      
